sudo: required
services: 
  - docker

before_install:
  - docker build -t perzefi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true perzefi/react-test npm test 

after_success:
  - docker build -t perzefi/multi-client ./client
  - docker build -t perzefi/multi-nginx ./nginx
  - docker build -t perzefi/multi-server ./server
  - docker build -t perzefi/multi-worker ./worker
  # Longin to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push to docker hub
  - docker push perzefi/multi-client
  - docker push perzefi/multi-nginx
  - docker push perzefi/multi-server
  - docker push perzefi/multi-worker